fmtrends.pdf: fmtrends.tex Makefile *.tex ../Common/*.tex ../Common/*.bib figures/*.pdf
	pdflatex $(@:%.pdf=%)
	bibtex $(@:%.pdf=%)
	pdflatex $(@:%.pdf=%)
	pdflatex $(@:%.pdf=%)
	pdflatex $(@:%.pdf=%)

clean:
	rm -f *.log *.blg *.bbl *.aux *.dvi *.out *.toc

clean-all: clean
	rm -f fmtrends.pdf

